#!/usr/bin/env node
/**
 * ONE-TIME SETUP. Creates the Ed25519 signing keypair for license issuing.
 *
 *   node tools/generate-keypair.js
 *
 * Writes:
 *   tools/keys/license-private.pem   <- SECRET. Never commit, never ship. Back it up.
 *   public/license/public-key.js     <- embedded in the app; safe to commit and ship.
 *
 * If you lose the private key you can no longer issue licenses for this public key,
 * and every already-activated machine keeps working. You would have to generate a new
 * pair and re-issue licenses on the next app update. Back up license-private.pem.
 */
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const KEY_DIR = path.join(__dirname, "keys");
const PRIVATE_PATH = path.join(KEY_DIR, "license-private.pem");
const PUBLIC_MODULE = path.join(ROOT, "public", "license", "public-key.js");

const force = process.argv.includes("--force");

if (fs.existsSync(PRIVATE_PATH) && !force) {
  console.error(
    `Refusing to overwrite an existing private key at:\n  ${PRIVATE_PATH}\n\n` +
      `Overwriting it invalidates every license you have already issued.\n` +
      `Pass --force only if you are certain.`
  );
  process.exit(1);
}

const { privateKey, publicKey } = crypto.generateKeyPairSync("ed25519");

const privatePem = privateKey.export({ type: "pkcs8", format: "pem" });
const publicPem = publicKey.export({ type: "spki", format: "pem" });

fs.mkdirSync(KEY_DIR, { recursive: true });
fs.writeFileSync(PRIVATE_PATH, privatePem, { mode: 0o600 });

fs.mkdirSync(path.dirname(PUBLIC_MODULE), { recursive: true });
fs.writeFileSync(
  PUBLIC_MODULE,
  `// AUTO-GENERATED by tools/generate-keypair.js -- do not edit by hand.\n` +
    `// This is the PUBLIC half of the license signing key. It is safe to ship.\n` +
    `// Licenses are minted with the matching private key, which lives only on the\n` +
    `// admin machine (tools/keys/license-private.pem, gitignored).\n` +
    `module.exports = ${JSON.stringify(publicPem)};\n`
);

console.log("Keypair generated.\n");
console.log(`  private (SECRET, gitignored): ${path.relative(ROOT, PRIVATE_PATH)}`);
console.log(`  public  (shipped in app):     ${path.relative(ROOT, PUBLIC_MODULE)}`);
console.log("\nBack up the private key somewhere safe and offline.");
